[package]
name = "terminal"
version = "0.1.0"
authors = ["BenJilks <benjyjilks@gmail.com>"]
edition = "2018"
links = "xlib"
build = "build.rs"

[dependencies]
x11 = "2.18.2"
libc = "0.2"

[profile.release]
opt-level = 2
debug = false
debug-assertions = false
overflow-checks = false
rpath = false

