#!/usr/bin/python

from pathlib import Path
from argparse import ArgumentParser
import os, json

BOOKMARK_FILE = '.bookmarks'
HOME = str(Path.home())
BOOKMARK_PATH = HOME + '/' + BOOKMARK_FILE

parser = ArgumentParser(description='Manage bookmarks')
parser.add_argument('-l', '--list', help='Show saved bookmarks', action='store_true')
parser.add_argument('-a', '--add', type=str, help='Add this directory as a bookmark')
parser.add_argument('-r', '--remove', type=str, help='Remove this directory from bookmarks')
parser.add_argument('-g', '--goto', type=str, help='Go to a bookmark')
args = parser.parse_args()

bookmarks = {}
if Path(BOOKMARK_PATH).is_file():
    try:
        bookmarks_file = open(BOOKMARK_PATH, 'r')
        bookmarks = json.loads(bookmarks_file.read())
        bookmarks_file.close()
    except:
        pass

if args.add:
    if args.add == '':
        print('Error: Must give a name')
        exit(-1)

    if args.add in bookmarks:
        print('Error: A bookmark with that name already exists')
        exit(-1)

    bookmarks[args.add] = os.getcwd()
elif args.remove:
    if args.remove == '':
        print('Error: Must give a name')
        exit(-1)

    if not args.remove in bookmarks:
        print('Error: No bookmark with that name found')
        exit(-1)

    del bookmarks[args.remove]
elif args.goto:
    if not args.goto in bookmarks:
        print('Error: No bookmark with that name found')
        exit(-1)
    
    os.chdir(bookmarks[args.goto])
    os.system('bash')
else:
    for bm in bookmarks:
        print(bm, '->', bookmarks[bm])

bookmarks_file = open(BOOKMARK_PATH, 'w')
bookmarks_file.write(json.dumps(bookmarks))
bookmarks_file.close()
